CREATE TABLE PRODUTO3 (ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                        NOME VARCHAR2(30),
                        TIPO VARCHAR2(30),
                        MARCAR VARCHAR2(30));
     
DECLARE

V_NOME PRODUTO3.NOME%TYPE := 'MOUSE';
V_TIPO PRODUTO3.TIPO%TYPE := 'PERIFERICO';
V_MARCAR PRODUTO3.MARCAR%TYPE := 'DELL';
                      
BEGIN

    INSERT INTO PRODUTO3 (NOME,TIPO,MARCAR) VALUES (V_NOME,V_TIPO,V_MARCAR);
    COMMIT;

END;